name: Publish to Github

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and generate lock file
        run: npm install

      - name: Run tests
        run: npm test

      - name: Publish to npm
        if: steps.version-bump.outputs.newTag != ''
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}